name = "Truelynautics"
author = "TruelySmol and Freddie_06"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7be4a3a84a788936c4a418efa3523239715985163ca091f86c75fa298d389b49"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
