name = "Truelynautics"
author = "TruelySmol and Freddie_06"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6a79ba2126fd0248741f50146d7b01c33f0beea24de988250390863b2c9ece5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
