name = "Truelynautics"
author = "TruelySmol and Freddie_06"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d39b58bcfe645eee7f0cfe3b4f8e0e5f94777ab0cf573c08c5c5f9b70da93005"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
